In progress re-write
Updated Files
 * Update: .github/workflows/build.yml
 * Update: bin/install
 * Update: bin/list-all

Deleted Files
 * Delete: bin/download
 * Delete: lib/utils.bash

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,11 +1,27 @@
 #!/usr/bin/env bash
 
-set -euo pipefail
+set -e
+set -o pipefail
 
-current_script_path=${BASH_SOURCE[0]}
-plugin_dir=$(dirname "$(dirname "$current_script_path")")
+ASDF_INSTALL_TYPE=${ASDF_INSTALL_TYPE:-version  }
+TMPDIR=${TMPDIR:-/tmp}
+[ -n "$ASDF_INSTALL_VERSION" ] || (>&2 echo 'Missing ASDF_INSTALL_VERSION' && exit 1)
+[ -n "$ASDF_INSTALL_PATH" ] || (>&2 echo 'Missing ASDF_INSTALL_PATH' && exit 1)
 
-# shellcheck source=../lib/utils.bash
-source "${plugin_dir}/lib/utils.bash"
+install_kubectx() {
+  # local install_type=$1           # not currently used
+  local version=$2
+  local install_path=$3
+  local bin_install_path="$install_path/bin"
+  local download_url; download_url="$(get_download_url "$version")"
 
-install_version "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
+  mkdir -p "${bin_install_path}"
+}
+
+
+get_download_url() {
+  local version="$1"
+  echo "https://github.com/kubepug/releases/archive/v${version}/kubepug_linux_amd64.tar.gz"
+}
+
+install_kubectx "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
