test new format
Updated Files
 * Update: bin/install

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -3,25 +3,63 @@
 set -e
 set -o pipefail
 
-ASDF_INSTALL_TYPE=${ASDF_INSTALL_TYPE:-version  }
-TMPDIR=${TMPDIR:-/tmp}
-[ -n "$ASDF_INSTALL_VERSION" ] || (>&2 echo 'Missing ASDF_INSTALL_VERSION' && exit 1)
-[ -n "$ASDF_INSTALL_PATH" ] || (>&2 echo 'Missing ASDF_INSTALL_PATH' && exit 1)
-
-install_kubectx() {
-  # local install_type=$1           # not currently used
+install_kubepug() {
+  local install_type=$1
   local version=$2
   local install_path=$3
+  local platform="$(uname | tr '[:upper:]' '[:lower:]')_$(get_arch)"
   local bin_install_path="$install_path/bin"
-  local download_url; download_url="$(get_download_url "$version")"
+  local binary_path="$bin_install_path/kubepug"
+  local release_file="$bin_install_path/kubepug.tar.gz"
+  local download_url=$(get_download_url $version $platform)
+
+  if [ "$TMPDIR" = "" ]; then
+    local tmp_download_dir=$(mktemp -d -t kubepug_XXXXXX)
+  else
+    local tmp_download_dir=$TMPDIR
+  fi
 
   mkdir -p "${bin_install_path}"
+
+  local download_path="$tmp_download_dir/$(get_filename $platform)"
+
+  echo "Downloading kubepug from ${download_url} to ${release_file}"
+  if curl -Lfs "${download_url}" -o "${release_file}"; then
+    #  Extract contents of tar.gz file into the download directory
+    echo $release_file
+    echo $binary_path
+    tar -xzf "$release_file" -C "$bin_install_path" || fail "Could not extract $release_file"
+
+    # Remove the tar.gz file since we don't need to keep it
+    rm "$release_file"
+    chmod +x "${binary_path}"
+  else
+    echo "Error: kubepug ${version} not found. Run 'asdf list-all kubepug' for available versions." >&2
+    exit 1
+  fi
 }
 
+get_arch() {
+  ARCH=$(uname -m)
+  case $ARCH in
+    x86_64) ARCH="amd64";;
+    arm64|aarch64) ARCH="arm64";;
+  esac
+  echo "$ARCH"
+}
+
+get_filename() {
+  local platform="$1"
+
+  echo "kubepug_${platform}.tar.gz"
+}
 
 get_download_url() {
   local version="$1"
-  echo "https://github.com/kubepug/releases/archive/v${version}/kubepug_linux_amd64.tar.gz"
+  local platform="$2"
+  local filename="$(get_filename ${platform})"
+
+  echo "https://github.com/rikatz/kubepug/releases/download/v${version}/${filename}"
 }
 
-install_kubectx "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
+install_kubepug $ASDF_INSTALL_TYPE $ASDF_INSTALL_VERSION $ASDF_INSTALL_PATH
